FROM node:22-alpine

ARG DB_URL

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY tsconfig.json ./tsconfig.json

COPY ./src ./src

COPY ./prisma/schema.prisma ./prisma/schema.prisma

COPY ./doc/openapi.yaml ./doc/openapi.yaml

ENV DB_URL ${DB_URL}

RUN npm run build 

EXPOSE ${SERVER_PORT}

CMD ["npm", "run", "start:dev_docker"]